version: 1
abis:
  reward_manager: reward_manager.json
  participant_register: participant_register.json
  erc20: erc20.json
  flare_systems_manager: flare_systems_manager.json
  submission: submission.json
  fast_updater: fast_updater.json
  relay: relay.json
  voter_registry: voter_registry.json
  entity_manager: entity_manager.json
